import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";

import "modern-css-reset/dist/reset.min.css";
import "@mantine/core/styles.css";

const notoSansJp = Noto_Sans_JP({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja" suppressHydrationWarning={true}>
			<head>
				<ColorSchemeScript defaultColorScheme="auto" />
			</head>
			<body className={`${notoSansJp.className}`}>
				<MantineProvider defaultColorScheme="auto">{children}</MantineProvider>
			</body>
		</html>
	);
}
